name: project-deployer
on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: cloning repo
        uses: actions/checkout@v4

      - name: run compose
        run: |
          pwd
          echo -------
          cd SpeedSolverAPI/
          docker-compose -f docker/docker-compose.yml --project-directory . up --build 
